export const MARBLE_ANIMATION_DURATION = 300;
export const SLEEP_BEFORE_START_GAME = 600;
export const SLEEP_BETWEEN_TURNS = 1500;
export const SLEEP_AFTER_TURN_DICE = 200;
export const SLEEP_BETWEEN_MOVES = MARBLE_ANIMATION_DURATION + 100;
export const STEP_WIDTH = 8.3333333333; // percent
export const STEP_GUTTER = 0.83333333333; // percent
export const PATH_STEPS_COUNT = 45;
export const STORAGE_KEY = 'store';
